exec-once = swww-daemon & waybar & mako
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# exec-once=hyprctl setcursor Bibata-Modern-Ice 24
exec-once = hypridle
exec-once = iio-hyprland
exec-once = easyeffects --gapplication-service &
